### ISSUE TITLE
Playlists screen requires extra horizontal scrolling on the iPhone.

### ISSUE THREAD

**Issue by rgelb** [fatihak/InkyPi#170]
Picture is better than a thousand words.  Video is worth a million.

https://github.com/user-attachments/assets/2fbceda0-243d-4395-8bc6-d6f047631e82

**Comment by phattmatt** [comment]
Same issue seen on my Android Phone.

https://github.com/user-attachments/assets/bc9ae314-fbd4-4a3a-affe-60cee25347e4

**Comment by phattmatt** [comment]
Looks like some minor div/css change would improve this slightly.

I suspect adding `flex-wrap: wrap;` to .plugin-item:

```CSS
.plugin-item {
    display: flex;
    flex-wrap: wrap;
    align-items: center;
    padding: 10px 25px 10px 40px;
    border-top: 2px solid #e0e0e0;
    gap: 10px;
}
```
Will help a little, but looks untidy without also:

- adding a DIV to separate the "Displayed Now" element
- adding a DIV to group the Refresh Time and the other buttons together.

Handling extra long names going off the screen is unlikely to be straightforward, as word wrap will have no effect (no whitespace, no words). Clipping the name, or allowing a scroll box are the 'best' choices.

Example with flex-wrap, but no extra DIVs:

![Image](https://github.com/user-attachments/assets/2fc986fa-aabe-4db4-bf18-aa51d149c44d)
